### PR TITLE
Fixes CPU, RAM and Disk queries.  Adds AgentID.

### PR DESCRIPTION
**Pull request by Zebble**
Fixes CPU, RAM, Disk and couple of other queries that changed in newer versions of TRMM.
Search by Agent uses the unique AgentID instead of hostname.

### CODE REVIEW

**Comment by TheMcSebi** [comment]
I don't know what happed but this json seems to have massive formatting errors.

**Comment by dinger1986** [comment]
Zebbles or the original?

**Comment by TheMcSebi** [comment]
Zebbles newly committed file

**Comment by dinger1986** [comment]
So I better not accept it then. I haven't tested as been too busy with other things recently

**Comment by dinger1986** [comment]
unsure if I should merge this as apparently there is issues with it, Ill leave it sitting for another month or so

**Comment by Zebble** [comment]
Sorry for the delay...  Not sure why my export looks so squirrely.  Let me give it another shot and re-submit?

**Comment by dinger1986** [comment]
Cool, yeah resubmit that's grand 👍

**Comment by Zebble** [comment]
I've updated the pull request.  Should work now.  I have no idea how I messed up the original export!

**Comment by dinger1986** [comment]
Ok. I'll PR it now

**Comment by Zebble** [comment]
Nevermind, CPU/RAM/Disk are still broken in some instances.  Working on it...

**Comment by Zebble** [comment]
Nevermind the nevermind.  It all works as-is.  Long day... :)

**Comment by dinger1986** [comment]
Lol cool

**Pull request merged**
